### ISSUE TITLE
Ayuda en ingreso de campos

### ISSUE THREAD

**Issue by pabloAmigo** [jmg93/torneos#10]
La profe dijo que agreguemos en color atenuado al lado de cada formulario , alguna indicacion sobre que es lo que tiene que ingresar el usuario

**Comment by pabloAmigo** [comment]
Este es hincha pelota pero lo vamos a tener que hacer creo....

Tambien lo que podemos hacer es que en la pantalla de cargar un resultado, muestre un cartelito en color atenuado (?) diciendo que se va tomar como que se jugo el partido SI SOLO SI se ingreso una fecha de partido...esto creo que es importante

**Comment by jmg93** [comment]
Casi completo, por ahi falta en algún campo, pero no hay nada importante para poner. Lo dejo abierto por las dudas

**Comment by pabloAmigo** [comment]
Buenisimo, creo que ya está. Lo unico que queda grande el texto de placeholder del input de DNI de jugador, no lo pude cambiar, capaz que es en mi caso nomas, habria que probarlo si te pasa a vos tambien.. Igual ya esta, de ultima cambiamos el texto. 
![image](https://cloud.githubusercontent.com/assets/9022046/11796696/5f896d9c-a29c-11e5-9b71-0741b6d0db9b.png)
