### ISSUE TITLE
Ingresar mal el mail creando equipo

### ISSUE THREAD

**Issue by pabloAmigo** [jmg93/torneos#5]
Te tira error fatal (blue screen (?) ) y queda trabado.

**Comment by jmg93** [comment]
No me paso nada en este caso.. Lo dejo abierto por las dudas

**Comment by pabloAmigo** [comment]
PAsa esto cuando pones un mail sin ".com" por ejemplo asi: 
![image](https://cloud.githubusercontent.com/assets/9022046/11763104/7c519e16-a0dc-11e5-9c22-1624d7305008.png)

Tira ese error en ingless y no te deja seguir, hay que volver atras
